/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbotugasbesar;

import static java.awt.image.ImageObserver.HEIGHT;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thesa
 */
public class daftarSewa extends javax.swing.JFrame {

    /**
     * Creates new form daftarSewa
     */
    String[] data;
    String url;
    File file;
    BufferedReader br;
    BufferedWriter bw;
    FileWriter fw;
    String nama, stringTanggal;
    
    DefaultTableModel modelTabelDaftarPenyewa;
    public daftarSewa() {
        initComponents();
        
        setLocationRelativeTo(this);
        setResizable(false);
        
        data = new String[4];
        modelTabelDaftarPenyewa = (DefaultTableModel)tabelDaftarPenyewa.getModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDaftarPenyewa = new javax.swing.JTable();
        tDelete = new javax.swing.JButton();
        tDetail = new javax.swing.JButton();
        tKembali = new javax.swing.JButton();
        tSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("DAFTAR PENYEWA");

        tabelDaftarPenyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Tanggal masuk", "Tanggal kembali", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelDaftarPenyewa);
        if (tabelDaftarPenyewa.getColumnModel().getColumnCount() > 0) {
            tabelDaftarPenyewa.getColumnModel().getColumn(0).setResizable(false);
            tabelDaftarPenyewa.getColumnModel().getColumn(1).setResizable(false);
            tabelDaftarPenyewa.getColumnModel().getColumn(2).setResizable(false);
            tabelDaftarPenyewa.getColumnModel().getColumn(3).setResizable(false);
        }

        tDelete.setText("DELETE");
        tDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDeleteActionPerformed(evt);
            }
        });

        tDetail.setText("DETAIL");
        tDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDetailActionPerformed(evt);
            }
        });

        tKembali.setText("KEMBALI");
        tKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tKembaliActionPerformed(evt);
            }
        });

        tSave.setText("SAVE");
        tSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tDelete)
                                .addGap(18, 18, 18)
                                .addComponent(tDetail)
                                .addGap(18, 18, 18)
                                .addComponent(tSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tKembali)))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tDelete)
                        .addComponent(tDetail)
                        .addComponent(tSave))
                    .addComponent(tKembali))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDetailActionPerformed
        // TODO add your handling code here:
        if(tabelDaftarPenyewa.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Harap Pilih Baris!", "Perhatian", HEIGHT);
        }
        else{
            dispose();
            DETAIL d = new DETAIL();
            d.setVisible(true);
        }
        
    }//GEN-LAST:event_tDetailActionPerformed

    private void tDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDeleteActionPerformed
        // TODO add your handling code here:
        if(tabelDaftarPenyewa.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Harap Pilih Baris!", "Perhatian", HEIGHT);
        }
        else{
            int line = tabelDaftarPenyewa.getSelectedRow();
            modelTabelDaftarPenyewa.removeRow(line);
        }
    }//GEN-LAST:event_tDeleteActionPerformed

    private void tKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tKembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        utama u = new utama();
        u.setVisible(true);
    }//GEN-LAST:event_tKembaliActionPerformed

    private void tSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSaveActionPerformed
        // TODO add your handling code here:
        saveData();
    }//GEN-LAST:event_tSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(daftarSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(daftarSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(daftarSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(daftarSewa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new daftarSewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tDelete;
    private javax.swing.JButton tDetail;
    private javax.swing.JButton tKembali;
    private javax.swing.JButton tSave;
    private javax.swing.JTable tabelDaftarPenyewa;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        modelTabelDaftarPenyewa.getDataVector().removeAllElements();
        url = "src/Database/daftarPenyewa.txt";
        file = new File(url);
        try{
            br = new BufferedReader(new FileReader(file));
            Object[] lData = br.lines().toArray();
            
            for (Object lData1 : lData) {
                String[] data = lData1.toString().split("\t");
                modelTabelDaftarPenyewa.addRow(data);
            }
        }catch(IOException e){
        }
    }
    
    private void saveData(){
        url = "src/Database/daftarPenyewa.txt";
        file = new File(url);
        try{
            bw = new BufferedWriter(new FileWriter(file));
            for(int i = 0;i < tabelDaftarPenyewa.getRowCount();i++){
                for(int j = 0;j < tabelDaftarPenyewa.getColumnCount();j++){
                    bw.write(tabelDaftarPenyewa.getValueAt(i, j).toString() + "\t");
                }
                bw.newLine();
            }
            bw.close();
        }catch(IOException e){
        }
    }
}
