/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pbotugasbesar;

import static java.awt.image.ImageObserver.HEIGHT;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Thesa
 */
public class tambahStok extends javax.swing.JFrame {

    /**
     * Creates new form tambahStok
     */
     String[] data;
     String url;
     File file;
     BufferedReader br;
     FileWriter fw;
     BufferedWriter bw;
     DefaultTableModel modelTabelTambahStok;
    public tambahStok() {
        initComponents();
        
        setLocationRelativeTo(this);
        setResizable(false);
        
        modelTabelTambahStok = (DefaultTableModel)tabelTambahStok.getModel();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldKodeStok = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldNamaStok = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fieldJumlahStok = new javax.swing.JTextField();
        tTambah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        fieldHargaStok = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelTambahStok = new javax.swing.JTable();
        tBatal = new javax.swing.JButton();
        tSimpan = new javax.swing.JButton();
        tUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("TAMBAH STOK");

        jLabel2.setText("KODE ");

        fieldKodeStok.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldKodeStok.setText(" ");
        fieldKodeStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldKodeStokActionPerformed(evt);
            }
        });
        fieldKodeStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldKodeStokKeyTyped(evt);
            }
        });

        jLabel3.setText("NAMA");

        fieldNamaStok.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldNamaStok.setText(" ");

        jLabel4.setText("JUMLAH");

        fieldJumlahStok.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldJumlahStok.setText(" ");
        fieldJumlahStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldJumlahStokKeyTyped(evt);
            }
        });

        tTambah.setText("TAMBAH");
        tTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTambahActionPerformed(evt);
            }
        });

        jLabel5.setText("HARGA");

        fieldHargaStok.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fieldHargaStok.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fieldHargaStokKeyTyped(evt);
            }
        });

        tabelTambahStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode", "Nama", "Jumlah", "Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tabelTambahStok.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(tabelTambahStok);

        tBatal.setText("BATAL");
        tBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBatalActionPerformed(evt);
            }
        });

        tSimpan.setText("SIMPAN");
        tSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSimpanActionPerformed(evt);
            }
        });

        tUpdate.setText("UPDATE");
        tUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(fieldKodeStok, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(fieldNamaStok, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(42, 42, 42)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(122, 122, 122)
                                                .addComponent(jLabel1)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tBatal)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tUpdate)
                                        .addGap(33, 33, 33)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldHargaStok)
                                    .addComponent(fieldJumlahStok, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(tTambah, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(tSimpan)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldKodeStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(fieldJumlahStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldNamaStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(fieldHargaStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tTambah, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tBatal)
                        .addComponent(tUpdate)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tSimpan)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldKodeStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldKodeStokActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fieldKodeStokActionPerformed

    private void tTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTambahActionPerformed
        // TODO add your handling code here:
        boolean kSama = false, nSama = false;
        for(int i = 0;i < tabelTambahStok.getRowCount();i++){
            if(fieldKodeStok.getText().equals(tabelTambahStok.getValueAt(i, 0))){
                kSama = true;
            }
            if(fieldNamaStok.getText().equals(tabelTambahStok.getValueAt(i, 1))){
                nSama = true;
            }
        }
        if(kSama){
            JOptionPane.showMessageDialog(null, "Kode Barang Kembar!", "Perhatian", HEIGHT);
        }
        if(nSama){
            JOptionPane.showMessageDialog(null, "Nama Barang Kembar!", "Perhatian", HEIGHT);
        }
        else if(!kSama && !nSama){
            if(fieldKodeStok.getText().equals("") ||
                    fieldNamaStok.getText().equals("") ||
                    fieldJumlahStok.getText().equals("") ||
                    fieldHargaStok.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Harap Lengkapi Data!", "Perhatian", HEIGHT);
            }
            else{
                data[0] = fieldKodeStok.getText();
                data[1] = fieldNamaStok.getText();
                data[2] = fieldJumlahStok.getText();
                data[3] = fieldHargaStok.getText();
                
                modelTabelTambahStok.addRow(data);
                
                fieldKodeStok.setText("");
                fieldNamaStok.setText("");
                fieldJumlahStok.setText("");
                fieldHargaStok.setText("");
            }
        }
    }//GEN-LAST:event_tTambahActionPerformed

    private void tSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSimpanActionPerformed
        // TODO add your handling code here:
        url = "src/Database/stok.txt";
        file = new File(url);
        try{
            bw = new BufferedWriter(new FileWriter(file));
            for(int i = 0;i < tabelTambahStok.getRowCount();i++){
                for(int j = 0;j < tabelTambahStok.getColumnCount();j++){
                    bw.write(tabelTambahStok.getValueAt(i, j).toString() + "\t");
                }
                bw.newLine();
            }
            bw.close();
        }catch(IOException e){
        }
    }//GEN-LAST:event_tSimpanActionPerformed

    private void fieldKodeStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldKodeStokKeyTyped
        // TODO add your handling code here:
         if(!(Character.isDigit(evt.getKeyChar()))){
            evt.consume();
         }
    }//GEN-LAST:event_fieldKodeStokKeyTyped

    private void fieldJumlahStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldJumlahStokKeyTyped
        // TODO add your handling code here:
         if(!(Character.isDigit(evt.getKeyChar()))){
            evt.consume();
         }
    }//GEN-LAST:event_fieldJumlahStokKeyTyped

    private void fieldHargaStokKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldHargaStokKeyTyped
        // TODO add your handling code here:
         if(!(Character.isDigit(evt.getKeyChar()))){
            evt.consume();
         }
    }//GEN-LAST:event_fieldHargaStokKeyTyped

    private void tBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBatalActionPerformed
        // TODO add your handling code here:
        fieldKodeStok.setText("");
        fieldNamaStok.setText("");
        fieldJumlahStok.setText("");
        fieldHargaStok.setText("");
    }//GEN-LAST:event_tBatalActionPerformed

    private void tUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tUpdateActionPerformed
        // TODO add your handling code here:
        if(fieldKodeStok.getText().equals("") ||
                fieldNamaStok.getText().equals("") ||
                fieldJumlahStok.getText().equals("") ||
                fieldHargaStok.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Harap Lengkapi Data!", "Perhatian", HEIGHT);
        }
        if(tabelTambahStok.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(null, "Harap Pilih Baris!", "Perhatian", HEIGHT);
        }
        else{
            data[0] = fieldKodeStok.getText();
            data[1] = fieldNamaStok.getText();
            data[2] = fieldJumlahStok.getText();
            data[3] = fieldHargaStok.getText();
            
            int line = tabelTambahStok.getSelectedRow();
            
            modelTabelTambahStok.setValueAt(data[0], line, 0);
            modelTabelTambahStok.setValueAt(data[1], line, 1);
            modelTabelTambahStok.setValueAt(data[2], line, 2);
            modelTabelTambahStok.setValueAt(data[3], line, 3);
            
            fieldKodeStok.setText("");
            fieldNamaStok.setText("");
            fieldJumlahStok.setText("");
            fieldHargaStok.setText("");
        }
    }//GEN-LAST:event_tUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahStok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahStok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldHargaStok;
    private javax.swing.JTextField fieldJumlahStok;
    private javax.swing.JTextField fieldKodeStok;
    private javax.swing.JTextField fieldNamaStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tBatal;
    private javax.swing.JButton tSimpan;
    private javax.swing.JButton tTambah;
    private javax.swing.JButton tUpdate;
    private javax.swing.JTable tabelTambahStok;
    // End of variables declaration//GEN-END:variables

    private void loadData() {
        modelTabelTambahStok.getDataVector().removeAllElements();
        url = "src/Database/stok.txt";
        file = new File(url);
        try{
            br = new BufferedReader(new FileReader(file));
           Object[] lData = br.lines().toArray();
            
            for (Object lData1 : lData) {
                String[] data = lData1.toString().split("\t");
                modelTabelTambahStok.addRow(data);
            }
        }catch(IOException e){
        }
    }
}
